import type { EquipmentSlot, ItemKind } from "@darkforest/protocol";
import { itemArtPathsFor as sharedItemArtPathsFor } from "@/browser/item_art.js";

export type ItemArtCategory = "weapon" | "equipment" | "footwear" | "supply";
export type ItemArtAccent = "cyan" | "amber" | "moss";

export interface ItemArtEntry {
  kind: ItemKind;
  name: string;
  englishName: string;
  category: ItemArtCategory;
  slot: EquipmentSlot | "weapon" | "inventory" | "insight";
  slotLabel: string;
  fieldIcon: string;
  cardArt: string;
  outlineIcon: string | null;
  silhouette: string;
  summary: string;
  accent: ItemArtAccent;
}

function sharedArt(kind: ItemKind) {
  const art = sharedItemArtPathsFor(kind);
  if (art === null) throw new Error(`Missing shared item art paths: ${kind}`);
  return art;
}

/**
 * title/description 是 zh-TW 原文,同時作為 SSR 預設值;實際顯示走 titleKey/descriptionKey
 * 由 i18n 在 client 端替換(慣例同 armory_rules.ts 的 effectKey/detailKey)。少了 key 的話,
 * 這幾行中文會在 en/ja/ko/zh-CN/vi 原樣留著。
 */
export const ITEM_ART_SECTIONS: ReadonlyArray<{
  id: ItemArtCategory;
  number: string;
  eyebrow: string;
  title: string;
  titleKey: string;
  description: string;
  descriptionKey: string;
}> = [
  {
    id: "weapon",
    number: "01",
    eyebrow: "IN HAND",
    titleKey: "armory.section.weapon.title",
    title: "武器",
    descriptionKey: "armory.section.weapon.description",
    description: "只靠外輪廓，就能在交火前分辨重量、射程與持握方式。",
  },
  {
    id: "equipment",
    number: "02",
    eyebrow: "LOADOUT",
    titleKey: "armory.section.equipment.title",
    title: "裝備",
    descriptionKey: "armory.section.equipment.description",
    description: "六槽裝備以材質、層次與體積區分；圖像不代替戰局中的即時數值。",
  },
  {
    id: "footwear",
    number: "03",
    eyebrow: "FOOTING",
    titleKey: "armory.section.footwear.title",
    title: "鞋具",
    descriptionKey: "armory.section.footwear.description",
    description: "鞋底與包頭輪廓提醒你：地面也是戰鬥的一部分。",
  },
  {
    id: "supply",
    number: "04",
    eyebrow: "FIELD SUPPLY",
    titleKey: "armory.section.supply.title",
    title: "物資與洞察",
    descriptionKey: "armory.section.supply.description",
    description: "醫療、彈藥、修繕、探測與 Echo 記憶，各自保留一眼可認的符號。",
  },
];

export const ITEM_ART_CATALOG = [
  {
    kind: "tool",
    name: "工具",
    englishName: "BREAKER TOOL",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("tool"),
    silhouette: "鉤口扳手與鈍頭破拆器",
    summary: "維修城市，也能在貼身距離替你開路。",
    accent: "cyan",
  },
  {
    kind: "pistol",
    name: "手槍",
    englishName: "SIDEARM",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("pistol"),
    silhouette: "厚實滑套、扳機環與短握把",
    summary: "緊湊、俐落，適合在掩體密集的空間交火。",
    accent: "amber",
  },
  {
    kind: "rifle",
    name: "步槍",
    englishName: "FIELD RIFLE",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("rifle"),
    silhouette: "分離槍托、機匣與長槍管",
    summary: "長輪廓讓遠處的人影在開火前就感到威脅。",
    accent: "amber",
  },
  {
    kind: "cleaver",
    name: "菜刀",
    englishName: "FIELD CLEAVER",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("cleaver"),
    silhouette: "寬刃、吊孔與短木柄",
    summary: "貼身快攻；狹窄空間比開闊地更容易施展。",
    accent: "amber",
  },
  {
    kind: "stool",
    name: "板凳",
    englishName: "FOLDING STOOL",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("stool"),
    silhouette: "厚座板、斜腳與交叉撐條",
    summary: "沉重鈍擊；傷害高，但每次揮動都很慢。",
    accent: "amber",
  },
  {
    kind: "golf_club",
    name: "高爾夫球桿",
    englishName: "SALVAGED IRON",
    category: "weapon",
    slot: "weapon",
    slotLabel: "手持武器",
    ...sharedArt("golf_club"),
    silhouette: "長握把、細桿身與偏置桿頭",
    summary: "需要完整揮動空間；在開闊地更能發揮。",
    accent: "cyan",
  },
  {
    kind: "cloth_jacket",
    name: "布上衣",
    englishName: "PATCH JACKET",
    category: "equipment",
    slot: "jacket",
    slotLabel: "上衣槽",
    ...sharedArt("cloth_jacket"),
    silhouette: "柔軟衣身、翻領與補丁",
    summary: "輕薄的城市工作服，提供最基礎的保護。",
    accent: "moss",
  },
  {
    kind: "stab_jacket",
    name: "防刺外套",
    englishName: "STAB JACKET",
    category: "equipment",
    slot: "jacket",
    slotLabel: "上衣槽",
    ...sharedArt("stab_jacket"),
    silhouette: "交疊防護層與加高領口",
    summary: "更厚的通用防護層；它不會額外抵抗特定武器。",
    accent: "amber",
  },
  {
    kind: "composite_chest",
    name: "複合胸甲",
    englishName: "COMPOSITE CHEST",
    category: "equipment",
    slot: "jacket",
    slotLabel: "上衣槽",
    ...sharedArt("composite_chest"),
    silhouette: "角形背心與分段胸板",
    summary: "多層板件構成主甲，也是最醒目的重裝輪廓。",
    accent: "amber",
  },
  {
    kind: "work_helmet",
    name: "工地頭盔",
    englishName: "WORK HELMET",
    category: "equipment",
    slot: "helmet",
    slotLabel: "頭盔槽",
    ...sharedArt("work_helmet"),
    silhouette: "硬帽圓頂、脊線與寬帽沿",
    summary: "從工地撿回來的可靠頭部防護。",
    accent: "amber",
  },
  {
    kind: "nvg_helmet",
    name: "夜視頭盔",
    englishName: "NIGHT-VISION HELMET",
    category: "equipment",
    slot: "helmet",
    slotLabel: "頭盔槽",
    ...sharedArt("nvg_helmet"),
    silhouette: "雙光學筒與前額支架",
    summary: "減輕黑暗對射擊的干擾，穿上時也會留下更明顯的訊號。",
    accent: "cyan",
  },
  {
    kind: "work_pants",
    name: "工作褲",
    englishName: "WORK PANTS",
    category: "equipment",
    slot: "pants",
    slotLabel: "下身槽",
    ...sharedArt("work_pants"),
    silhouette: "分腿衣身、口袋與護膝片",
    summary: "耐磨布料與多一只口袋，為長途搜索而生。",
    accent: "moss",
  },
  {
    kind: "rough_gloves",
    name: "粗手套",
    englishName: "ROUGH GLOVES",
    category: "equipment",
    slot: "gloves",
    slotLabel: "手套槽",
    ...sharedArt("rough_gloves"),
    silhouette: "粗面掌墊與短袖口",
    summary: "簡單的掌面護甲；不會改變搜刮速度或結果。",
    accent: "moss",
  },
  {
    kind: "labor_gloves",
    name: "勞工手套",
    englishName: "LABOR GLOVES",
    category: "equipment",
    slot: "gloves",
    slotLabel: "手套槽",
    ...sharedArt("labor_gloves"),
    silhouette: "關節護條與抓握紋",
    summary: "替雙手與工具承受反覆工作的磨耗。",
    accent: "cyan",
  },
  {
    kind: "leather_gloves",
    name: "皮革護手",
    englishName: "LEATHER GUARDS",
    category: "equipment",
    slot: "gloves",
    slotLabel: "手套槽",
    ...sharedArt("leather_gloves"),
    silhouette: "長袖口與 V 形皮革縫線",
    summary: "厚皮護住手腕，外形也比一般工作手套更硬。",
    accent: "amber",
  },
  {
    kind: "small_backpack",
    name: "小背包",
    englishName: "SMALL PACK",
    category: "equipment",
    slot: "backpack",
    slotLabel: "背包槽",
    ...sharedArt("small_backpack"),
    silhouette: "緊湊主艙與單前袋",
    summary: "不拖慢腳步的基本攜行空間。",
    accent: "cyan",
  },
  {
    kind: "large_backpack",
    name: "大背包",
    englishName: "LARGE PACK",
    category: "equipment",
    slot: "backpack",
    slotLabel: "背包槽",
    ...sharedArt("large_backpack"),
    silhouette: "高身主艙、側袋與壓縮帶",
    summary: "大幅增加攜行容量，不會額外拖慢移動或暴露輪廓。",
    accent: "amber",
  },
  {
    kind: "soft_sole",
    name: "軟底鞋",
    englishName: "SOFT-SOLE SHOES",
    category: "footwear",
    slot: "shoes",
    slotLabel: "鞋具槽",
    ...sharedArt("soft_sole"),
    silhouette: "低筒鞋身與分段柔底",
    summary: "低矮、柔韌，視覺上屬於安靜行動的鞋具。",
    accent: "cyan",
  },
  {
    kind: "steel_toe",
    name: "鋼頭鞋",
    englishName: "STEEL-TOE BOOTS",
    category: "footwear",
    slot: "shoes",
    slotLabel: "鞋具槽",
    ...sharedArt("steel_toe"),
    silhouette: "高筒靴身、鞋帶與金屬包頭",
    summary: "沉重而可靠，一眼就能認出強化鞋頭。",
    accent: "amber",
  },
  {
    kind: "light_ammo",
    name: "輕彈",
    englishName: "LIGHT AMMO",
    category: "supply",
    slot: "inventory",
    slotLabel: "背包物資",
    ...sharedArt("light_ammo"),
    silhouette: "成對彈殼與彈頭",
    summary: "射擊武器的有限補給；數量仍以戰局文字為準。",
    accent: "amber",
  },
  {
    kind: "bandage",
    name: "繃帶",
    englishName: "FIELD BANDAGE",
    category: "supply",
    slot: "inventory",
    slotLabel: "醫療物資",
    ...sharedArt("bandage"),
    silhouette: "交疊布卷與固定帶",
    summary: "快速止血的基礎醫療物資。",
    accent: "moss",
  },
  {
    kind: "medkit",
    name: "醫療包",
    englishName: "MEDKIT",
    category: "supply",
    slot: "inventory",
    slotLabel: "醫療物資",
    ...sharedArt("medkit"),
    silhouette: "提把硬盒與縫合帶標記",
    summary: "完整的現場醫療包，沒有借用現實組織的紅十字符號。",
    accent: "moss",
  },
  {
    kind: "healthy_food",
    name: "完整口糧",
    englishName: "SEALED RATION",
    category: "supply",
    slot: "inventory",
    slotLabel: "恢復物資",
    ...sharedArt("healthy_food"),
    silhouette: "密封口糧袋、葉片與穀粒標記",
    summary: "能同時補回少量生命與大量氣力的可靠口糧。",
    accent: "moss",
  },
  {
    kind: "spoiled_food",
    name: "腐敗食物",
    englishName: "SPOILED RATION",
    category: "supply",
    slot: "inventory",
    slotLabel: "應急物資",
    ...sharedArt("spoiled_food"),
    silhouette: "膨脹破損的口糧袋、腐斑與飛蟲",
    summary: "能救急回復氣力，但會讓腸胃不適並暫停自然回氣。",
    accent: "amber",
  },
  {
    kind: "scrap",
    name: "廢料",
    englishName: "SALVAGE SCRAP",
    category: "supply",
    slot: "inventory",
    slotLabel: "維修物資",
    ...sharedArt("scrap"),
    silhouette: "斷齒片、螺栓與金屬碎塊",
    summary: "城市殘骸留下的修繕材料。",
    accent: "amber",
  },
  {
    kind: "trap_scanner",
    name: "陷阱掃描器",
    englishName: "TRAP SCANNER",
    category: "supply",
    slot: "inventory",
    slotLabel: "戰術物資",
    ...sharedArt("trap_scanner"),
    silhouette: "手持框體、雷達環與掃描扇",
    summary: "揭露目前地點的導電積水；每次掃描都會升高訊號。",
    accent: "cyan",
  },
  {
    kind: "insight_root_sense",
    name: "根系感知",
    englishName: "ROOT SENSE",
    category: "supply",
    slot: "insight",
    slotLabel: "Echo 洞察",
    ...sharedArt("insight_root_sense"),
    silhouette: "眼形核心與分岔根鬚",
    summary: "沿根系邊緣揭露端點的導電積水；它不是導航指引。",
    accent: "moss",
  },
  {
    kind: "insight_calamity_echo",
    name: "災變殘響",
    englishName: "CALAMITY ECHO",
    category: "supply",
    slot: "insight",
    slotLabel: "Echo 洞察",
    ...sharedArt("insight_calamity_echo"),
    silhouette: "裂滴核心與向外殘響波",
    summary: "揭露一個已知地點的危險，並短暫免疫該處災害。",
    accent: "cyan",
  },
] as const satisfies ReadonlyArray<ItemArtEntry>;

export function itemArtFor(kind: ItemKind): ItemArtEntry {
  const entry = ITEM_ART_CATALOG.find((candidate) => candidate.kind === kind);
  if (entry === undefined) throw new Error(`Missing item art entry: ${kind}`);
  return entry;
}
